accounts/urls.py
# coding=utf-8

from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^cadastro/$', views.register, name="register"),
    url(r'^alterar-dados/$', views.update_user, name="update_user"),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
]

catalogo/urls.py
# coding=utf-8

from django.conf.urls import url
from django.core.exceptions import ImproperlyConfigured
from . import views

app_name = 'categoria'
urlpatterns = [
    url(r'^$', views.produtos, name="produtos"),
 	url(r'^promocoes/$', views.promocoes, name='promocoes'),
 	url(r'^(?P<slug>[\w_-]+)/$', views.categoria, name='categoria'),
 	url(r'^produtos/(?P<slug>[\w_-]+)/$', views.produto, name='produto'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url
from django.core.exceptions import ImproperlyConfigured
from . import views

app_name = 'compras'
urlpatterns = [
    url(r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cart_item, name="create_cart_item"),
 	url(r'^carrinho/$', views.cart_item, name='cart_item'),
 	url(r'^finalizacao/$', views.checkout, name='checkout'),
	url(
        r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view,
        name='pagseguro_view'
	),
	url(
        r'^notificacoes/pagseguro/$', views.pagseguro_notification,
        name='pagseguro_notification'
    ),
 	url(r'^meus_pedidos/$', views.order_list, name='order_list'),		
 	url(r'^detalhes_do_pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from core import views
from catalogo import views as views_catalogo
from checkout import views as views_checkout

from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^catalogo/', include('catalogo.urls', namespace='catalogo')),
    url(r'^contato/$', views.contato, name="contato"),
    url(r'^compras/', include('checkout.urls', namespace="checkout")),
    url(r'^pesquisa/', include('pesquisa.urls', namespace="pesquisa")),
    url(r'^entrar/$', login, {'template_name':'login.html'}, name="login"),
    url(r'^sair/$', logout, {'next_page':'index'}, name="logout"),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

checkout/models.py
# coding=utf-8

from pagseguro import PagSeguro

from django.db import models
from django.conf import settings

from catalogo.models import Product


class CartItemManager(models.Manager):

    def add_item(self, cart_key, product):
        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        else:
            created = True
            cart_item = CartItem.objects.create(
                cart_key=cart_key, product=product, price=product.price
            )
        return cart_item, created


class CartItem(models.Model):

    cart_key = models.CharField(
        'Chave do Carrinho', max_length=40, db_index=True
    )
    product = models.ForeignKey('catalogo.Product', verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    objects = CartItemManager()

    class Meta:
        verbose_name = 'Item do Carrinho'
        verbose_name_plural = 'Itens dos Carrinhos'
        unique_together = (('cart_key', 'product'),)

    def __str__(self):
        return '{} [{}]'.format(self.product, self.quantity)


class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, quantity=cart_item.quantity, product=cart_item.product,
                price=cart_item.price
            )
        return order


class Order(models.Model):

    STATUS_CHOICES = (
        (0, 'Aguardando Pagamento'),
        (1, 'Concluída'),
        (2, 'Cancelada'),
    )

    PAYMENT_OPTION_CHOICES = (
        ('deposit', 'Depósito'),
        ('pagseguro', 'PagSeguro'),
        ('paypal', 'Paypal'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário')
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=0, blank=True
    )
    payment_option = models.CharField(
        'Opção de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20,
        default='deposit'
    )

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    def products(self):
        products_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=products_ids)

    def total(self):
        aggregate_queryset = self.items.aggregate(
            total=models.Sum(
                models.F('price') * models.F('quantity'),
                output_field=models.DecimalField()
            )
        )
        return aggregate_queryset['total']

    def pagseguro_update_status(self, status):
        if status == '3':
            self.status = 1
        elif status == '7':
            self.status = 2
        self.save()

    def complete(self):
        self.status = 1
        self.save()

    def pagseguro(self):
        self.payment_option = 'pagseguro'
        self.save()
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SANDBOX}
        )
        pg.sender = {
            'email': self.user.email
        }
        pg.reference_prefix = ''
        pg.shipping = None
        pg.reference = self.pk
        for item in self.items.all():
            pg.items.append(
                {
                    'id': item.product.pk,
                    'description': item.product.name,
                    'quantity': item.quantity,
                    'amount': '%.2f' % item.price
                }
            )
        return pg

class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='items')
    product = models.ForeignKey('catalogo.Product', verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens dos pedidos'

    def __str__(self):
        return '[{}] {}'.format(self.order, self.product)


def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()


models.signals.post_save.connect(
    post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item'
)

checkout/views.py
# coding=utf-8

from pagseguro import PagSeguro

from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (
    RedirectView, TemplateView, ListView, DetailView
)
from django.forms import modelformset_factory
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.conf import settings
from django.http import HttpResponse

from catalogo.models import Product

from .models import CartItem, Order


class CreateCartItemView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        product = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CartItem.objects.add_item(
            self.request.session.session_key, product
        )
        if created:
            messages.success(self.request, 'Produto adicionado com sucesso')
        else:
            messages.success(self.request, 'Produto atualizado com sucesso')
        return reverse('checkout:cart_item')


class CartItemView(TemplateView):

    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
        CartItemFormSet = modelformset_factory(
            CartItem, fields=('quantity',), can_delete=True, extra=0
        )
        session_key = self.request.session.session_key
        if session_key:
            if clear:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key)
                )
            else:
                formset = CartItemFormSet(
                    queryset=CartItem.objects.filter(cart_key=session_key),
                    data=self.request.POST or None
                )
        else:
            formset = CartItemFormSet(queryset=CartItem.objects.none())
        return formset

    def get_context_data(self, **kwargs):
        context = super(CartItemView, self).get_context_data(**kwargs)
        context['formset'] = self.get_formset()
        return context

    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)


class CheckoutView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(
                user=request.user, cart_items=cart_items
            )
            cart_items.delete()
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response


class OrderListView(LoginRequiredMixin, ListView):

    template_name = 'checkout/order_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('-pk')


class OrderDetailView(LoginRequiredMixin, DetailView):

    template_name = 'checkout/order_detail.html'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class PagSeguroView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        order_pk = self.kwargs.get('pk')
        order = get_object_or_404(
            Order.objects.filter(user=self.request.user), pk=order_pk
        )
        pg = order.pagseguro()
        pg.redirect_url = self.request.build_absolute_uri(
            reverse('checkout:order_detail', args=[order.pk])
        )
        #pg.notification_url = self.request.build_absolute_uri(
         #   reverse('checkout:pagseguro_notification')
        #)
        response = pg.checkout()
        return response.payment_url

@csrf_exempt
def pagseguro_notification(request):
    notification_code = request.POST.get('notificationCode', None)
    if notification_code:
        pg = PagSeguro(
            email=settings.PAGSEGURO_EMAIL, token=settings.PAGSEGURO_TOKEN,
            config={'sandbox': settings.PAGSEGURO_SANDBOX}
        )
        notification_data = pg.check_notification(notification_code)
        status = notification_data.status
        reference = notification_data.reference
        try:
            order = Order.objects.get(pk=reference)
        except Order.DoesNotExist:
            pass
        else:
            order.pagseguro_update_status(status)
    return HttpResponse('OK')


create_cart_item = CreateCartItemView.as_view()
cart_item = CartItemView.as_view()
checkout = CheckoutView.as_view()
order_list = OrderListView.as_view()
order_detail = OrderDetailView.as_view()
pagseguro_view = PagSeguroView.as_view()

checkout/templates/checkout/cart.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
Carrinho de Compras
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li class="active">Carrinho de Compras</li>
</ol>
<div class="page-header">
    <h1>Carrinho de Compras</h1>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
<form class="" action="" method="post">
    {% csrf_token %}
    <table class="table table-bordered">
    {{ formset.management_form }}
    <thead>
        <th>
            ID
        </th>
        <th>
            Nome
        </th>
        <th>
            Preço
        </th>
        <th style="width: 10%;">
            Quantidade
        </th>
        <th>

        </th>
    </thead>
    <tbody>
        {% for form in formset %}
        <tr>
            <td>
                {{ form.instance.product.pk }}
            </td>
            <td>
                {{ form.instance.product }}
            </td>
            <td>
                R$ {{ form.instance.price|floatformat:"2" }}
            </td>
            <td>
                {% render_field form.quantity class='form-control' %}
            </td>
            <td class="text-center">
                <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="btn btn-danger btn-sm">remover</button>
                {{ form.id }}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'catalogo:produtos' %}" class="pull-left btn btn-default">Continuar Compras</a>
        <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
        <a href="{% url 'checkout:checkout' %}" class="btn btn-success">Finalizar Compra</a>
    </p>
</form>
</div>
</div>
{% endblock %}

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
    Método de pagamento | {{ block.super }}
{% endblock title %}

{% block container %}
        <div class="page-header">
			<h1>Escolha a forma de pagamento</h1>
        </div>
        <div class="row">
        <p> Pedido #{{ order.pk }}</p>
            <div class="col-md-8 col-md-offset-2">
                <p>Deposite o dinheiro na conta: 818.3003.0101.222.20303 e dê três mortais para trás para confirmar o pedido</p>
            </div>
        </div>
{% endblock container %}

checkout/templates/checkout/order_detail.html
{% extends "accounts/index.html" %}

{% block title %}
    Pedido #{{ order.pk }}
{% endblock title %}
{% block accounts_container %}
<h2> Pedido #{{order.pk}}</h2>
<strong>Detalhes: </strong>
<dl class="dl-horizontal">	
	<dt>Total: R$</dt>
	<dd> {{object.total|floatformat:"2"}}</dd>
	<dt>Situação</dt>
	<dd>{{ object.get_status_display }}</dd>
	<dt>Data</dt>
	<dd>{{object.created|date:"d/m/Y H:i"}}</dd>
	<dt>Forma de pagamento:</dt>
	<dd>{{ object.get_payment_option_display}}</dd>
</dl>
<h3>Itens do pedido</h3>
{% for item in object.items.all %}
<dl class="dl-horizontal">	
	<dt>Produto</dt>
	<dd>{{ item.product }}</dd>
	<dt>Quantidade</dt>
	<dd>{{ item.quantity }}</dd>
	<dt>Preço </dt>
	<dd>R$ {{ item.price|floatformat:"2" }}</dd>
</dl>
{% endfor %}

{% endblock %}

checkout/templates/checkout/order_list.html
{% extends "accounts/index.html" %}


{% load pagination %}
{% block title %}
    Meus pedidos
{% endblock title %}
{% block accounts_container %}
<h2>Meus pedidos</h2>
<table class="table table-striped table-bordered">	
	<thead>	
			<tr>
				<th>Nº</th>
				<th>Produtos</th>
				<th>Situação</th>
				<th>Data do pedido</th>
			</tr>
		<tbody>
			{% for order in object_list %}
			<tr>	
				<td><a href="{% url 'checkout:order_detail' order.pk %}">#{{order.pk}}</a></td>
				<td>
					{% for product in order.products %}
						<h5>
						{{product.name}}{% if not forloop.last %}<br> {%endif%}
						</h5>
					{% endfor %}
				</td>
				<td> {{ order.get_status_display }}</td>
				<td> {{ order.created|date:"d/m/Y"}} </td>
			</tr>	
			{% endfor %}
		</tbody>
	</thead>

</table>
{% pagination request paginator page_obj %}
{% endblock %}