accounts/urls.py
# coding=utf-8

from django.conf.urls import url
from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^cadastro/$', views.register, name="register"),
    url(r'^alterar-dados/$', views.update_user, name="update_user"),
    url(r'^alterar-senha/$', views.update_password, name='update_password'),
]

catalogo/urls.py
# coding=utf-8

from django.conf.urls import url
from django.core.exceptions import ImproperlyConfigured
from . import views

app_name = 'categoria'
urlpatterns = [
    url(r'^$', views.produtos, name="produtos"),
 	url(r'^promocoes/$', views.promocoes, name='promocoes'),
 	url(r'^(?P<slug>[\w_-]+)/$', views.categoria, name='categoria'),
 	url(r'^produtos/(?P<slug>[\w_-]+)/$', views.produto, name='produto'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url
from django.core.exceptions import ImproperlyConfigured
from . import views

app_name = 'compras'
urlpatterns = [
    url(r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$', views.create_cart_item, name="create_cart_item"),
 	url(r'^carrinho/$', views.cart_item, name='cart_item'),
 	url(r'^finalizacao/$', views.checkout, name='checkout'),
	url(
        r'^finalizando/(?P<pk>\d+)/pagseguro/$', views.pagseguro_view,
        name='pagseguro_view'
	),
	url(
        r'^notificacoes/pagseguro/$', views.pagseguro_notification,
        name='pagseguro_notification'
    ),
 	url(r'^meus_pedidos/$', views.order_list, name='order_list'),		
 	url(r'^detalhes_do_pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from core import views
from catalogo import views as views_catalogo
from checkout import views as views_checkout

from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^catalogo/', include('catalogo.urls', namespace='catalogo')),
    url(r'^contato/$', views.contato, name="contato"),
    url(r'^compras/', include('checkout.urls', namespace="checkout")),
    url(r'^pesquisa/', include('pesquisa.urls', namespace="pesquisa")),
    url(r'^entrar/$', login, {'template_name':'login.html'}, name="login"),
    url(r'^sair/$', logout, {'next_page':'index'}, name="logout"),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

pesquisa/urls.py
# coding=utf-8

from django.conf.urls import url
from django.core.exceptions import ImproperlyConfigured
from . import views

app_name = 'pesquisa'
urlpatterns = [
	url(r'^', views.pesquisa, name="pesquisa"),
]

core/models.py
from django.db import models

class Banner(models.Model):
	image = models.ImageField('Banner', upload_to='banner')
	nome = models.CharField('Nome', max_length=100)
	promovido = models.BooleanField("Página principal")

	class Meta:
		verbose_name = 'Banner'
		verbose_name_plural = 'Banners'

	def __str__(self):
		return self.nome

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .form import ContactForm
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.views.generic import View, TemplateView, CreateView
from catalogo.models import Category, Product
from django.views import generic
from .models import Banner


class indexProdutos(generic.ListView):
	
	model = Product
	template_name = 'index.html'
	context_object_name = 'produtos'

	def get_queryset(self):
		return Product.objects.filter(promotional=True)

	def get_context_data(self, **kwargs):
		context = super(indexProdutos, self).get_context_data(**kwargs)
		context['banner'] = Banner.objects.filter(promovido=True)
		return context

index = indexProdutos.as_view()

def contato(request):
	success = False
	form = ContactForm(request.POST or None)
	request.session['teste'] = 'teste'
	if form.is_valid():
		form.send_mail()
		success = True
	context = {
		'form': form,
		'success': success
	}
	return render(request, 'contato.html', context)

User = get_user_model()

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang='pt-br'>
<head>
	<meta charset="utf-8">
	<title>{% block title %} Django E-commerce{% endblock title %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.css' %}" media="screen" />
  <link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/shop-item.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">{{ title }}</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
                {% for category in categorias %}
                  <li><a href="{{ category.get_absolute_url }}">{{category}}</a></li>
                {% endfor %}
                  <li><a href="{% url 'catalogo:promocoes'%}">Promocoes</a></li>
              </ul>
            </li>
    			<li>
    				<a href="{% url 'contato' %}">Contato</a>
    			</li>
          <li>
              <form method="get" action="{%url 'pesquisa:pesquisa' %}" class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" name="name" placeholder="Pesquisa">
                  <input type="hidden" class="form-control" name="tipo" value="nome" placeholder="Pesquisa">
                </div>
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
              </form>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Sair</a></li>
            <li><a href="{% url 'accounts:index' %}">Olá, {{user}}</a></li>
            <li><a href="{% url 'accounts:index' %}">Conta</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            <li><a href="{% url 'accounts:register' %}">Cadastro</a></li>
            {% endif %}
            <li><a href="{%url 'checkout:cart_item' %}">Carrinho</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">

		{% block messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            {{message}}
          </div>
        {%endfor%}
    {% endblock messages %}
    {% block container %}
		    
		{% endblock container %}
  </div>
    <div class="container">
    <footer>
        <div class="col-lg-10">
          <ul class="list-unstyled">
            <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
            <li><a href="{% url 'index' %}">Início</a></li>
            <li><a href="{% url 'catalogo:produtos' %}">Produtos</a></li>
            <li><a href="{% url 'contato' %}">Contato</a></li>
            <li><a href="">Termos e Privacidade</a></li>
          </ul>
        </div>
    </footer>
    </div>
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

core/templates/contato.html
{% extends "base.html" %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    <form class="form-horizontal" action="http://52.54.242.89:90/api/emailAPI" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {{ field }}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
    Página Inicial | {{ block.super }}
{% endblock title %}

{% block container %}    
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
  {% for imagem in banner|slice:':4' %}
    {% if forloop.first %}
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    {% else %}
    <li data-target="#myCarousel" data-slide-to="{{forloop.counter|add:'-1'}}"></li>
    {% endif %}
  {% endfor %}
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  {% for imagem in banner|slice:':4' %}
    {% if forloop.first %}
    <div class="item active">
    {% else %}
    <div class="item">
    {% endif %}
      <img class="img-total img-responsive" src="{{imagem.image|thumbnail_url:'banner_home'}}" alt="{{imagem.image.nome}}">
    </div>
  {% endfor %}
  </div>
  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Próxima</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
</div>
	<div style="display: flex; flex-wrap: nowrap;justify-content: space-around;">
		{% for category in categorias|slice:"5" %}
			<a class="bg-primary text-center category" 
			style="" href="{{ category.get_absolute_url }}">
				{{ category }}
			</a>
        {% endfor %}
  </div>    
	<div class="page-header">
  <div class="cinza">
		<h2 class="text-center text-uppercase"><a href="{% url 'catalogo:promocoes' %}">Promoções</a></h2>
    <p class="text-center">Confira as nossas promoções</p>
    {% for produto in produtos|slice:"3 " %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <a href="{{produto.get_absolute_url}}">
        <img src="http://placehold.it/350x250" alt="" />
      </a>
      <div class="caption">
        <h3>{{produto.name}}</h3>
        <p>{{produto.description|linebreaks}}.</p>
        <p>Preço:de <del>R${{produto.price}}</del> por R${{produto.promotional_price}}</p>
        <p><a href="{{ produto.get_absolute_url }}" class="btn btn-success" role="button">Saiba Mais</a> <a href="{% url 'checkout:create_cart_item' produto.slug %}" class="btn btn-default" role="button">Adicionar ao carrinho</a></p>
      </div>
    </div>
  </div>
  {% endfor %}
    </div>
  </div>
{% endblock container %}

    

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% block title %}
    Entrar | {{ block.super }}
{% endblock title %}

{% block container %}
<div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="page-header">
                    <h1>Entrar</h1>
                </div>
                <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error }}
                  </div>
                {% endfor %}
                    <fieldset>
                        <div class="form-group {% if form.has_errors %} has-error {% endif %}">
                          <label for="{{ form.username.auto_id}}" class="col-md-3 control-label">{{form.username.label}}</label>
                          <div class="col-md-9">
                              {% render_field form.username class="form-control" %}
                              {% for error in form.username.non_field_errors %}
                                <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>
                        <div class="form-group">
                          <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{form.password.label}}</label>
                          <div class="col-md-9">
                            {% render_field form.password class="form-control" %}
                              {% for error in form.password.errors %}
                                <span class="help-block">{{ error }}</span>
                              {% endfor %}
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                            <a href="{% url 'accounts:register' %}" type="submit" class="btn btn-success">Criar conta</a>
                          </div>
                        </div>
                    </fieldset>
                </form>
            </div>
  </div>
</div>
{% endblock container %}

core/templates/pagination.html
<div class="row">
	<div class="col-md-12">
		<ul class="pagination">
			{% for page in paginator.page_range	%}	
			<li {% if page_obj.number == page %} class="active" {% endif %}  ><a href="?page={{page}}">{{ page }}</a></li>
			{% endfor %}
		</ul>	
	</div>	
</div>